version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.20.1
    restart: always
    volumes:
      - ./prometheus_config/:/etc/prometheus/
      - prometheus_data:/prometheus
  grafana:
    image: grafana/grafana:7.1.3
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
    depends_on:
      - prometheus

volumes:
  prometheus_data:
  grafana_data:

networks:
  default:
    external:
      name: nginx-proxy