version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.25.0
    restart: always
    volumes:
      - ./prometheus_config/:/etc/prometheus/
      - prometheus_data:/prometheus
    networks:
      - default  
      
  grafana:
    image: grafana/grafana:7.4.2
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD
      - VIRTUAL_HOST
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
    networks:
      - default
      - proxy
    depends_on:
      - prometheus

volumes:
  prometheus_data:
  grafana_data:

networks:
  proxy:
    external:
      name: nginx-proxy
